module.exports = {
  configuracion: {
    dolar_blue: "1480.00",
    dolar_oficial: "1050.00",
    dolar_tarjeta: "1600.00",
    nombre_local: "New Point Store & Lab",
    moneda_default: "USD"
  },
  vendedores: [
    { id: 1, nombre: "NP", porcentaje_comision: 10, activo: true },
    { id: 2, nombre: "Eze", porcentaje_comision: 10, activo: true },
    { id: 3, nombre: "Mardel", porcentaje_comision: 10, activo: true },
    { id: 4, nombre: "Fran", porcentaje_comision: 10, activo: true },
    { id: 5, nombre: "Lara", porcentaje_comision: 10, activo: true },
    { id: 6, nombre: "Ger", porcentaje_comision: 10, activo: true },
    { id: 7, nombre: "Lourdes", porcentaje_comision: 10, activo: true }
  ],
  cuentas_caja: [
    { id: 1, nombre: "Caja Fuerte Dólares", tipo: "Caja Fuerte USD", moneda: "USD", saldo_inicial: 1470, saldo_actual: 1470, activo: true },
    { id: 2, nombre: "Caja Fuerte Pesos", tipo: "Caja Fuerte Pesos", moneda: "ARS", saldo_inicial: 193200, saldo_actual: 193200, activo: true },
    { id: 3, nombre: "Banco Galicia / Transferencias", tipo: "Banco", moneda: "ARS", saldo_inicial: 0, saldo_actual: 0, activo: true },
    { id: 4, nombre: "Lemon Cash / Cripto", tipo: "Billetera Virtual", moneda: "USDT", saldo_inicial: 0, saldo_actual: 0, activo: true },
    { id: 5, nombre: "Dólares Cara Chica", tipo: "Cara Chica", moneda: "USD", saldo_inicial: 0, saldo_actual: 0, activo: true },
    { id: 6, nombre: "Caja Reales", tipo: "Reales", moneda: "BRL", saldo_inicial: 0, saldo_actual: 0, activo: true },
    { id: 7, nombre: "Caja Euros", tipo: "Euros", moneda: "EUR", saldo_inicial: 0, saldo_actual: 0, activo: true }
  ],
  entidades_cc: [
    { id: 1, nombre: "Garden", tipo: "PROVEEDOR", contacto: "Garden Oficial", moneda_principal: "USD", saldo_adeudado: 10314, notas: "Proveedor mayorista de iPhones nuevos y sellados" },
    { id: 2, nombre: "Lucas Moroni", tipo: "PROVEEDOR", contacto: "Lucas M", moneda_principal: "USD", saldo_adeudado: 2025, notas: "Proveedor de equipos usados y nuevos seleccionados" },
    { id: 3, nombre: "Victor Diaz", tipo: "PROVEEDOR", contacto: "Victor Diaz", moneda_principal: "USD", saldo_adeudado: 0, notas: "Equipos y repuestos" },
    { id: 4, nombre: "Agus Black Apple", tipo: "PROVEEDOR", contacto: "Agus B", moneda_principal: "USD", saldo_adeudado: 2025, notas: "Proveedor" },
    { id: 5, nombre: "Rosario Técnica", tipo: "TECNICO", contacto: "Rosario Lab", moneda_principal: "USD", saldo_adeudado: 0, notas: "Taller externo especializado en placas y pantallas" },
    { id: 6, nombre: "Apple Becker", tipo: "TECNICO", contacto: "Becker", moneda_principal: "USD", saldo_adeudado: 0, notas: "Reparaciones y tapas traseras" },
    { id: 7, nombre: "Huevo y Alegre", tipo: "TECNICO", contacto: "Taller H&A", moneda_principal: "USD", saldo_adeudado: 0, notas: "Módulos y cambios de batería" },
    { id: 8, nombre: "Soulfix Repuestos", tipo: "PROVEEDOR", contacto: "Soulfix", moneda_principal: "ARS", saldo_adeudado: 0, notas: "Módulos y pegamentos" },
    { id: 9, nombre: "Zani Repuestos", tipo: "PROVEEDOR", contacto: "Zani", moneda_principal: "ARS", saldo_adeudado: 0, notas: "Baterías y flex" },
    { id: 10, nombre: "Ema Haase", tipo: "SOCIO", contacto: "Ema", moneda_principal: "USD", saldo_adeudado: 446, notas: "Socio / Cuentas" },
    { id: 11, nombre: "Ezequiel Mora", tipo: "SOCIO", contacto: "Eze", moneda_principal: "ARS", saldo_adeudado: 0, notas: "Socio / Operaciones" },
    { id: 12, nombre: "German Falcone", tipo: "SOCIO", contacto: "German", moneda_principal: "USD", saldo_adeudado: 0, notas: "Socio" },
    { id: 13, nombre: "Bauti Righini", tipo: "SOCIO", contacto: "Bauti", moneda_principal: "USD", saldo_adeudado: -5, notas: "Cuenta de socio" },
    { id: 14, nombre: "Munchi", tipo: "SOCIO", contacto: "Munchi", moneda_principal: "USD", saldo_adeudado: 1320, notas: "Cuenta corriente" }
  ],
  dispositivos: [
    {
        "id": 101,
        "modelo": "iPhone 14 Pro Max",
        "color": "Purple",
        "capacidad": "256GB",
        "bateria": 78,
        "imei": "354155091238491",
        "condicion": "Usado (Lente reparado)",
        "costo_usd": 530,
        "costo_pesos": 0,
        "costo_reparacion_usd": 50,
        "precio_sugerido_usd": 650,
        "precio_sugerido_pesos": 975000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "Reparación de lente efectuada"
    },
    {
        "id": 102,
        "modelo": "iPhone 14 Pro",
        "color": "Negro",
        "capacidad": "128GB",
        "bateria": 85,
        "imei": "355536081293847",
        "condicion": "Usado",
        "costo_usd": 375,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 480,
        "precio_sugerido_pesos": 720000,
        "proveedor": "Lucas Moroni",
        "estado": "En Stock",
        "detalles": "Original 85% batería"
    },
    {
        "id": 103,
        "modelo": "iPhone 14",
        "color": "Negro",
        "capacidad": "128GB",
        "bateria": 85,
        "imei": "358546029384729",
        "condicion": "Usado",
        "costo_usd": 360,
        "costo_pesos": 0,
        "costo_reparacion_usd": 10,
        "precio_sugerido_usd": 470,
        "precio_sugerido_pesos": 705000,
        "proveedor": "Victor Diaz",
        "estado": "En Stock",
        "detalles": "Funda y cargador"
    },
    {
        "id": 104,
        "modelo": "iPhone 13",
        "color": "Negro",
        "capacidad": "128GB",
        "bateria": 87,
        "imei": "354455019283746",
        "condicion": "Usado",
        "costo_usd": 300,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 410,
        "precio_sugerido_pesos": 615000,
        "proveedor": "Victor Diaz",
        "estado": "En Stock",
        "detalles": "Original"
    },
    {
        "id": 105,
        "modelo": "iPhone 14",
        "color": "Lila",
        "capacidad": "128GB",
        "bateria": 84,
        "imei": "355168019283745",
        "condicion": "Usado",
        "costo_usd": 405,
        "costo_pesos": 0,
        "costo_reparacion_usd": 30,
        "precio_sugerido_usd": 520,
        "precio_sugerido_pesos": 780000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "Con accesorios"
    },
    {
        "id": 106,
        "modelo": "iPhone 13",
        "color": "Rojo",
        "capacidad": "128GB",
        "bateria": 94,
        "imei": "350016091823746",
        "condicion": "Usado Impecable",
        "costo_usd": 270,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 380,
        "precio_sugerido_pesos": 570000,
        "proveedor": "Lucas Moroni",
        "estado": "En Stock",
        "detalles": "94% de batería (Cliente NP)"
    },
    {
        "id": 107,
        "modelo": "iPhone 17 E",
        "color": "Blanco",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "359974019283747",
        "condicion": "Nuevo Sellado",
        "costo_usd": 640,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 780,
        "precio_sugerido_pesos": 1170000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "Nuevo en caja"
    },
    {
        "id": 108,
        "modelo": "iPhone 14",
        "color": "Negro",
        "capacidad": "128GB",
        "bateria": 79,
        "imei": "354155019283748",
        "condicion": "Usado",
        "costo_usd": 350,
        "costo_pesos": 0,
        "costo_reparacion_usd": 30,
        "precio_sugerido_usd": 450,
        "precio_sugerido_pesos": 675000,
        "proveedor": "Vlaen / Clienta NP",
        "estado": "En Stock",
        "detalles": "79% batería"
    },
    {
        "id": 109,
        "modelo": "iPhone 14 Pro",
        "color": "Purple",
        "capacidad": "128GB",
        "bateria": 79,
        "imei": "350016091823749",
        "condicion": "Usado",
        "costo_usd": 400,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 520,
        "precio_sugerido_pesos": 780000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "79% batería"
    },
    {
        "id": 110,
        "modelo": "iPhone 13",
        "color": "Rojo",
        "capacidad": "128GB",
        "bateria": 84,
        "imei": "351284091827365",
        "condicion": "Usado",
        "costo_usd": 280,
        "costo_pesos": 0,
        "costo_reparacion_usd": 55,
        "precio_sugerido_usd": 380,
        "precio_sugerido_pesos": 570000,
        "proveedor": "Cliente NP",
        "estado": "En Stock",
        "detalles": "84% batería"
    },
    {
        "id": 111,
        "modelo": "iPhone 15 Pro",
        "color": "Blue (Tapa)",
        "capacidad": "256GB",
        "bateria": 79,
        "imei": "358798019283747",
        "condicion": "Usado",
        "costo_usd": 490,
        "costo_pesos": 0,
        "costo_reparacion_usd": 107,
        "precio_sugerido_usd": 650,
        "precio_sugerido_pesos": 975000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "Cambio de tapa trasera"
    },
    {
        "id": 112,
        "modelo": "iPhone 12 Pro",
        "color": "Blue",
        "capacidad": "256GB",
        "bateria": 77,
        "imei": "356656019283747",
        "condicion": "Usado",
        "costo_usd": 180,
        "costo_pesos": 0,
        "costo_reparacion_usd": 35,
        "precio_sugerido_usd": 300,
        "precio_sugerido_pesos": 450000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "77% batería"
    },
    {
        "id": 113,
        "modelo": "iPhone 17",
        "color": "Blanco",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "359974019283746",
        "condicion": "Nuevo Sellado",
        "costo_usd": 970,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1210,
        "precio_sugerido_pesos": 1815000,
        "proveedor": "Cliente Mardel",
        "estado": "En Stock",
        "detalles": "256GB Nuevo"
    },
    {
        "id": 114,
        "modelo": "Samsung Galaxy S25 Ultra",
        "color": "Blanco",
        "capacidad": "512GB",
        "bateria": 100,
        "imei": "356656019283746",
        "condicion": "Nuevo",
        "costo_usd": 960,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1180,
        "precio_sugerido_pesos": 1770000,
        "proveedor": "Cliente Newpoint",
        "estado": "En Stock",
        "detalles": "512GB Nuevo"
    },
    {
        "id": 115,
        "modelo": "iPhone 15 Pro Max",
        "color": "Negro",
        "capacidad": "256GB",
        "bateria": 86,
        "imei": "353238019283747",
        "condicion": "Usado",
        "costo_usd": 700,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 880,
        "precio_sugerido_pesos": 1320000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "86% batería"
    },
    {
        "id": 116,
        "modelo": "iPhone 11",
        "color": "Negro",
        "capacidad": "256GB",
        "bateria": 85,
        "imei": "357420019283747",
        "condicion": "Usado",
        "costo_usd": 250,
        "costo_pesos": 0,
        "costo_reparacion_usd": 30,
        "precio_sugerido_usd": 350,
        "precio_sugerido_pesos": 525000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "Batería cambiada"
    },
    {
        "id": 117,
        "modelo": "iPhone 8 Plus",
        "color": "Lavender",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "2235316850",
        "condicion": "Nuevo",
        "costo_usd": 180,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 260,
        "precio_sugerido_pesos": 390000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "256GB Lavender"
    },
    {
        "id": 118,
        "modelo": "iPhone 16 Pro",
        "color": "Blanco",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "351284091827366",
        "condicion": "Nuevo Sellado",
        "costo_usd": 970,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1150,
        "precio_sugerido_pesos": 1725000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "Batería 100%"
    },
    {
        "id": 119,
        "modelo": "iPhone 16 Pro",
        "color": "Blanco",
        "capacidad": "256GB",
        "bateria": 94,
        "imei": "358798019283748",
        "condicion": "Usado",
        "costo_usd": 950,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1125,
        "precio_sugerido_pesos": 1687500,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "94% batería"
    },
    {
        "id": 120,
        "modelo": "iPhone 15 Pro",
        "color": "Natural Titanium",
        "capacidad": "256GB",
        "bateria": 94,
        "imei": "356656019283748",
        "condicion": "Usado Impecable",
        "costo_usd": 775,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 920,
        "precio_sugerido_pesos": 1380000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "94% batería"
    },
    {
        "id": 121,
        "modelo": "iPhone 15 Pro",
        "color": "Blue",
        "capacidad": "128GB",
        "bateria": 88,
        "imei": "353238019283748",
        "condicion": "Usado",
        "costo_usd": 550,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 690,
        "precio_sugerido_pesos": 1035000,
        "proveedor": "Garden",
        "estado": "En Stock",
        "detalles": "88% batería"
    },
    {
        "id": 122,
        "modelo": "Samsung Galaxy S26 Ultra",
        "color": "Violeta",
        "capacidad": "512GB",
        "bateria": 100,
        "imei": "357420019283748",
        "condicion": "Nuevo",
        "costo_usd": 1180,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1360,
        "precio_sugerido_pesos": 2040000,
        "proveedor": "Roxana Clienta NP",
        "estado": "En Stock",
        "detalles": "512GB Violeta Nuevo"
    },
    {
        "id": 123,
        "modelo": "iPhone 17 Pro Max",
        "color": "Silver",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "351284091827367",
        "condicion": "Nuevo Sellado",
        "costo_usd": 1290,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1450,
        "precio_sugerido_pesos": 2175000,
        "proveedor": "Mely Clienta NP",
        "estado": "En Stock",
        "detalles": "256GB Silver Nuevo"
    },
    {
        "id": 124,
        "modelo": "Samsung Galaxy S22 Ultra",
        "color": "Violeta",
        "capacidad": "256GB",
        "bateria": 85,
        "imei": "358798019283749",
        "condicion": "Usado",
        "costo_usd": 160,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 260,
        "precio_sugerido_pesos": 390000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "S22 Ultra Usado"
    },
    {
        "id": 125,
        "modelo": "iPhone 13 Pro",
        "color": "Blue",
        "capacidad": "128GB",
        "bateria": 100,
        "imei": "356656019283749",
        "condicion": "Usado",
        "costo_usd": 410,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 520,
        "precio_sugerido_pesos": 780000,
        "proveedor": "Cliente EMA",
        "estado": "En Stock",
        "detalles": "100% batería"
    },
    {
        "id": 126,
        "modelo": "iPhone 17",
        "color": "Negro",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "353238019283749",
        "condicion": "Nuevo Sellado",
        "costo_usd": 970,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1180,
        "precio_sugerido_pesos": 1770000,
        "proveedor": "Cliente EMA",
        "estado": "En Stock",
        "detalles": "256GB Negro Nuevo"
    },
    {
        "id": 127,
        "modelo": "iPhone 17 Pro Max",
        "color": "Silver",
        "capacidad": "256GB",
        "bateria": 85,
        "imei": "2234237951",
        "condicion": "Usado",
        "costo_usd": 1200,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1380,
        "precio_sugerido_pesos": 2070000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "Usado 256GB"
    },
    {
        "id": 128,
        "modelo": "iPhone 13",
        "color": "Negro",
        "capacidad": "128GB",
        "bateria": 78,
        "imei": "357420019283749",
        "condicion": "Usado",
        "costo_usd": 150,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 260,
        "precio_sugerido_pesos": 390000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "78% batería"
    },
    {
        "id": 129,
        "modelo": "iPhone 17 Pro Max",
        "color": "Silver",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "351284091827368",
        "condicion": "Nuevo Sellado",
        "costo_usd": 1290,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1450,
        "precio_sugerido_pesos": 2175000,
        "proveedor": "Víctor reventa",
        "estado": "En Stock",
        "detalles": "256GB Silver Nuevo"
    },
    {
        "id": 130,
        "modelo": "iPhone 16",
        "color": "Pink",
        "capacidad": "128GB",
        "bateria": 89,
        "imei": "358798019283750",
        "condicion": "Usado",
        "costo_usd": 590,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 720,
        "precio_sugerido_pesos": 1080000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "89% batería"
    },
    {
        "id": 131,
        "modelo": "iPhone 15",
        "color": "Azul",
        "capacidad": "128GB",
        "bateria": 100,
        "imei": "356656019283750",
        "condicion": "Nuevo Sellado",
        "costo_usd": 695,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 820,
        "precio_sugerido_pesos": 1230000,
        "proveedor": "Marcelo Cliente NP",
        "estado": "En Stock",
        "detalles": "Nuevo sellado"
    },
    {
        "id": 132,
        "modelo": "iPhone 16",
        "color": "Blanco",
        "capacidad": "128GB",
        "bateria": 100,
        "imei": "353238019283750",
        "condicion": "Usado Impecable",
        "costo_usd": 650,
        "costo_pesos": 0,
        "costo_reparacion_usd": 10,
        "precio_sugerido_usd": 780,
        "precio_sugerido_pesos": 1170000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "100% batería"
    },
    {
        "id": 133,
        "modelo": "iPhone 13 Pro",
        "color": "Sierra Blue",
        "capacidad": "128GB",
        "bateria": 78,
        "imei": "357420019283750",
        "condicion": "Usado",
        "costo_usd": 370,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 490,
        "precio_sugerido_pesos": 735000,
        "proveedor": "Valen Clienta NP",
        "estado": "En Stock",
        "detalles": "78% batería"
    },
    {
        "id": 134,
        "modelo": "iPhone 13",
        "color": "Rojo",
        "capacidad": "256GB",
        "bateria": 89,
        "imei": "351284091827369",
        "condicion": "Usado",
        "costo_usd": 300,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 420,
        "precio_sugerido_pesos": 630000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "89% batería"
    },
    {
        "id": 135,
        "modelo": "MacBook Air M2",
        "color": "Starlight",
        "capacidad": "512GB",
        "bateria": 100,
        "imei": "358798019283751",
        "condicion": "Nuevo",
        "costo_usd": 1200,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1450,
        "precio_sugerido_pesos": 2175000,
        "proveedor": "Cliente mardel",
        "estado": "En Stock",
        "detalles": "M2 Starlight 512GB"
    },
    {
        "id": 136,
        "modelo": "MacBook Air M5",
        "color": "Starlight",
        "capacidad": "512GB",
        "bateria": 100,
        "imei": "356656019283751",
        "condicion": "Nuevo",
        "costo_usd": 1400,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1650,
        "precio_sugerido_pesos": 2475000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "512GB Nuevo"
    },
    {
        "id": 137,
        "modelo": "iPhone 16",
        "color": "Negro",
        "capacidad": "128GB",
        "bateria": 93,
        "imei": "353238019283751",
        "condicion": "Usado",
        "costo_usd": 635,
        "costo_pesos": 0,
        "costo_reparacion_usd": 5,
        "precio_sugerido_usd": 760,
        "precio_sugerido_pesos": 1140000,
        "proveedor": "Esmeralda Clienta NP",
        "estado": "En Stock",
        "detalles": "93% batería"
    },
    {
        "id": 138,
        "modelo": "iPhone 17 Pro",
        "color": "Blue",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "357420019283751",
        "condicion": "Nuevo Sellado",
        "costo_usd": 1210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1380,
        "precio_sugerido_pesos": 2070000,
        "proveedor": "Chavo",
        "estado": "En Stock",
        "detalles": "256GB Blue Nuevo"
    },
    {
        "id": 139,
        "modelo": "iPhone 16",
        "color": "Azul",
        "capacidad": "128GB",
        "bateria": 89,
        "imei": "351284091827370",
        "condicion": "Usado",
        "costo_usd": 610,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 730,
        "precio_sugerido_pesos": 1095000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "89% batería"
    },
    {
        "id": 140,
        "modelo": "iPhone 16",
        "color": "Teal",
        "capacidad": "512GB",
        "bateria": 100,
        "imei": "358798019283752",
        "condicion": "Nuevo",
        "costo_usd": 880,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1050,
        "precio_sugerido_pesos": 1575000,
        "proveedor": "Valentina Giordano",
        "estado": "En Stock",
        "detalles": "512GB Teal"
    },
    {
        "id": 141,
        "modelo": "iPhone 17 Pro Max",
        "color": "Silver",
        "capacidad": "256GB",
        "bateria": 100,
        "imei": "356656019283752",
        "condicion": "Nuevo Sellado",
        "costo_usd": 1300,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 1480,
        "precio_sugerido_pesos": 2220000,
        "proveedor": "Clienta NP",
        "estado": "En Stock",
        "detalles": "256GB Silver"
    },
    {
        "id": 142,
        "modelo": "iPhone 15 Pro Max",
        "color": "Natural Titanium",
        "capacidad": "256GB",
        "bateria": 89,
        "imei": "353238019283752",
        "condicion": "Usado (Pantalla)",
        "costo_usd": 500,
        "costo_pesos": 0,
        "costo_reparacion_usd": 140,
        "precio_sugerido_usd": 720,
        "precio_sugerido_pesos": 1080000,
        "proveedor": "Local",
        "estado": "En Taller",
        "detalles": "Cambio de pantalla"
    },
    {
        "id": 143,
        "modelo": "iPhone 15 Pro",
        "color": "Natural Titanium",
        "capacidad": "256GB",
        "bateria": 86,
        "imei": "357420019283752",
        "condicion": "Usado Impecable",
        "costo_usd": 590,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 720,
        "precio_sugerido_pesos": 1080000,
        "proveedor": "Local",
        "estado": "En Stock",
        "detalles": "86% batería"
    },
    {
        "id": 144,
        "modelo": "iPhone 11",
        "color": "Violeta",
        "capacidad": "64GB",
        "bateria": 81,
        "imei": "356564019283746",
        "condicion": "Usado",
        "costo_usd": 210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 310,
        "precio_sugerido_pesos": 465000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "81% Batería Guerrero"
    },
    {
        "id": 145,
        "modelo": "iPhone 11",
        "color": "Negro",
        "capacidad": "64GB",
        "bateria": 82,
        "imei": "356861019283746",
        "condicion": "Usado",
        "costo_usd": 210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 310,
        "precio_sugerido_pesos": 465000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "82% Batería Guerrero"
    },
    {
        "id": 146,
        "modelo": "iPhone 11",
        "color": "Blanco",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "351089019283746",
        "condicion": "Usado",
        "costo_usd": 215,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 315,
        "precio_sugerido_pesos": 472500,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "83% Batería Guerrero"
    },
    {
        "id": 147,
        "modelo": "iPhone 11",
        "color": "Blanco",
        "capacidad": "64GB",
        "bateria": 81,
        "imei": "355436019283746",
        "condicion": "Usado",
        "costo_usd": 210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 310,
        "precio_sugerido_pesos": 465000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "81% Batería Guerrero"
    },
    {
        "id": 148,
        "modelo": "iPhone 11",
        "color": "Negro",
        "capacidad": "64GB",
        "bateria": 81,
        "imei": "356314019283746",
        "condicion": "Usado",
        "costo_usd": 210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 310,
        "precio_sugerido_pesos": 465000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "81% Batería Guerrero"
    },
    {
        "id": 149,
        "modelo": "iPhone 11",
        "color": "Blanco",
        "capacidad": "64GB",
        "bateria": 82,
        "imei": "355436029384756",
        "condicion": "Usado",
        "costo_usd": 210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 310,
        "precio_sugerido_pesos": 465000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "82% Batería Guerrero"
    },
    {
        "id": 150,
        "modelo": "iPhone 11",
        "color": "Negro",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "356314029384756",
        "condicion": "Usado",
        "costo_usd": 215,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 315,
        "precio_sugerido_pesos": 472500,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "83% Batería Guerrero"
    },
    {
        "id": 151,
        "modelo": "iPhone 11",
        "color": "Negro",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "355126019283746",
        "condicion": "Usado",
        "costo_usd": 215,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 315,
        "precio_sugerido_pesos": 472500,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "83% Batería Guerrero"
    },
    {
        "id": 152,
        "modelo": "iPhone 11",
        "color": "Verde",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "352791019283746",
        "condicion": "Usado",
        "costo_usd": 215,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 315,
        "precio_sugerido_pesos": 472500,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "83% Batería Guerrero"
    },
    {
        "id": 153,
        "modelo": "iPhone 12",
        "color": "Verde",
        "capacidad": "64GB",
        "bateria": 86,
        "imei": "352485019283746",
        "condicion": "Usado",
        "costo_usd": 280,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 390,
        "precio_sugerido_pesos": 585000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "86% Batería Guerrero"
    },
    {
        "id": 154,
        "modelo": "iPhone 12",
        "color": "Azul",
        "capacidad": "64GB",
        "bateria": 80,
        "imei": "359670019283746",
        "condicion": "Usado",
        "costo_usd": 270,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 375,
        "precio_sugerido_pesos": 562500,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "80% Batería Guerrero"
    },
    {
        "id": 155,
        "modelo": "iPhone 12",
        "color": "Blanco",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "355985019283746",
        "condicion": "Usado",
        "costo_usd": 280,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 390,
        "precio_sugerido_pesos": 585000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "83% Batería Guerrero"
    },
    {
        "id": 156,
        "modelo": "iPhone 12",
        "color": "Negro",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "350839019283746",
        "condicion": "Usado",
        "costo_usd": 280,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 390,
        "precio_sugerido_pesos": 585000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "83% Batería Guerrero"
    },
    {
        "id": 157,
        "modelo": "iPhone 13 Pro Max",
        "color": "Gold",
        "capacidad": "128GB",
        "bateria": 82,
        "imei": "352206019283746",
        "condicion": "Usado Impecable",
        "costo_usd": 490,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 620,
        "precio_sugerido_pesos": 930000,
        "proveedor": "Martin Olmos (Guerrero)",
        "estado": "En Stock",
        "detalles": "82% Gold Guerrero"
    },
    {
        "id": 158,
        "modelo": "iPhone 11",
        "color": "Negro",
        "capacidad": "64GB",
        "bateria": 75,
        "imei": "356700019283746",
        "condicion": "Usado",
        "costo_usd": 195,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 290,
        "precio_sugerido_pesos": 435000,
        "proveedor": "Martin Olmos",
        "estado": "En Stock",
        "detalles": "75% Batería"
    },
    {
        "id": 159,
        "modelo": "iPhone 13",
        "color": "Rojo",
        "capacidad": "256GB",
        "bateria": 88,
        "imei": "356700029384756",
        "condicion": "Usado",
        "costo_usd": 310,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 430,
        "precio_sugerido_pesos": 645000,
        "proveedor": "Martin Olmos",
        "estado": "En Stock",
        "detalles": "256GB Rojo"
    },
    {
        "id": 160,
        "modelo": "iPhone 11",
        "color": "Blanco",
        "capacidad": "128GB",
        "bateria": 85,
        "imei": "356700039485767",
        "condicion": "Usado",
        "costo_usd": 240,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 340,
        "precio_sugerido_pesos": 510000,
        "proveedor": "Martin Olmos",
        "estado": "En Stock",
        "detalles": "128GB Blanco"
    },
    {
        "id": 161,
        "modelo": "iPhone 14",
        "color": "Negro",
        "capacidad": "256GB",
        "bateria": 89,
        "imei": "358798029384756",
        "condicion": "Usado Impecable",
        "costo_usd": 390,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 510,
        "precio_sugerido_pesos": 765000,
        "proveedor": "Martin Olmos",
        "estado": "En Stock",
        "detalles": "256GB Negro"
    },
    {
        "id": 162,
        "modelo": "iPhone 11",
        "color": "Blanco",
        "capacidad": "64GB",
        "bateria": 82,
        "imei": "356656029384756",
        "condicion": "Usado",
        "costo_usd": 210,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 310,
        "precio_sugerido_pesos": 465000,
        "proveedor": "Martin Olmos",
        "estado": "En Stock",
        "detalles": "64GB Blanco"
    },
    {
        "id": 163,
        "modelo": "iPhone 13 Pro Max",
        "color": "Gold",
        "capacidad": "256GB",
        "bateria": 85,
        "imei": "358409019283746",
        "condicion": "Usado Impecable",
        "costo_usd": 520,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 660,
        "precio_sugerido_pesos": 990000,
        "proveedor": "Martin Olmos",
        "estado": "En Stock",
        "detalles": "Gold 256GB"
    },
    {
        "id": 164,
        "modelo": "iPhone 13",
        "color": "Azul",
        "capacidad": "128GB",
        "bateria": 88,
        "imei": "350555029384756",
        "condicion": "Usado",
        "costo_usd": 290,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 400,
        "precio_sugerido_pesos": 600000,
        "proveedor": "Pilar Rivero",
        "estado": "En Stock",
        "detalles": "13 Azul Impecable"
    },
    {
        "id": 165,
        "modelo": "iPhone 13",
        "color": "Rojo",
        "capacidad": "128GB",
        "bateria": 86,
        "imei": "350555019283746",
        "condicion": "Usado",
        "costo_usd": 285,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 395,
        "precio_sugerido_pesos": 592500,
        "proveedor": "Pilar Rivero",
        "estado": "En Stock",
        "detalles": "13 Rojo"
    },
    {
        "id": 166,
        "modelo": "iPhone 12 Pro",
        "color": "Blanco",
        "capacidad": "128GB",
        "bateria": 84,
        "imei": "350906019283746",
        "condicion": "Usado",
        "costo_usd": 310,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 420,
        "precio_sugerido_pesos": 630000,
        "proveedor": "Pilar Rivero",
        "estado": "En Stock",
        "detalles": "12 Pro Blanco"
    },
    {
        "id": 167,
        "modelo": "iPhone XR",
        "color": "Blanco",
        "capacidad": "64GB",
        "bateria": 83,
        "imei": "350906029384756",
        "condicion": "Usado",
        "costo_usd": 140,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 220,
        "precio_sugerido_pesos": 330000,
        "proveedor": "Cliente Ger",
        "estado": "En Stock",
        "detalles": "XR 64GB Blanco"
    },
    {
        "id": 168,
        "modelo": "iPhone 13",
        "color": "Azul",
        "capacidad": "128GB",
        "bateria": 87,
        "imei": "353238039485767",
        "condicion": "Usado",
        "costo_usd": 290,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 400,
        "precio_sugerido_pesos": 600000,
        "proveedor": "Guerrero",
        "estado": "En Stock",
        "detalles": "13 Azul Guerrero"
    },
    {
        "id": 169,
        "modelo": "iPhone 12 Pro",
        "color": "Azul",
        "capacidad": "128GB",
        "bateria": 85,
        "imei": "357420039485767",
        "condicion": "Usado",
        "costo_usd": 315,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 425,
        "precio_sugerido_pesos": 637500,
        "proveedor": "Matias Faiad",
        "estado": "En Stock",
        "detalles": "12 Pro Azul"
    },
    {
        "id": 170,
        "modelo": "iPhone 11 Pro",
        "color": "Grafito",
        "capacidad": "64GB",
        "bateria": 84,
        "imei": "353238029384756",
        "condicion": "Usado",
        "costo_usd": 250,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 350,
        "precio_sugerido_pesos": 525000,
        "proveedor": "Matias Faiad",
        "estado": "En Stock",
        "detalles": "11 Pro Grafito"
    },
    {
        "id": 171,
        "modelo": "iPhone 12 Pro Max",
        "color": "Blanco",
        "capacidad": "128GB",
        "bateria": 86,
        "imei": "357420049586778",
        "condicion": "Usado Impecable",
        "costo_usd": 410,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 540,
        "precio_sugerido_pesos": 810000,
        "proveedor": "Julieta Cliente NP",
        "estado": "En Stock",
        "detalles": "12 Pro Max Blanco"
    },
    {
        "id": 172,
        "modelo": "iPhone 12 Pro",
        "color": "Azul",
        "capacidad": "256GB",
        "bateria": 87,
        "imei": "357420019283746",
        "condicion": "Usado Impecable",
        "costo_usd": 340,
        "costo_pesos": 0,
        "costo_reparacion_usd": 0,
        "precio_sugerido_usd": 460,
        "precio_sugerido_pesos": 690000,
        "proveedor": "Julieta Cliente NP",
        "estado": "En Stock",
        "detalles": "12 Pro Azul 256GB"
    }
],
  deudas_deudores: [
    { id: 1, tipo: "DEUDOR", persona: "German Falcone", concepto: "Diferencia préstamo / equipo", monto_original: 99, monto_pendiente: 99, moneda: "USD", estado: "Pendiente" },
    { id: 2, tipo: "DEUDOR", persona: "Dario Mecánico", concepto: "Equipos entregados", monto_original: 285, monto_pendiente: 285, moneda: "USD", estado: "Pendiente" },
    { id: 3, tipo: "DEUDOR", persona: "Iñaki Mar del Plata", concepto: "Saldo 2 equipos", monto_original: 443, monto_pendiente: 443, moneda: "USD", estado: "Pendiente" },
    { id: 4, tipo: "DEUDA", persona: "Préstamo Richard", concepto: "Inversión inicial capital", monto_original: 8000, monto_pendiente: 8000, moneda: "USD", estado: "Pendiente" }
  ],
  inversiones: [
    { id: 1, item: "Antena Starlink Kit", valor_usd: 400, valor_pesos: 0, contacto_proveedor: "Starlink", categoria: "Equipamiento" },
    { id: 2, item: "Contadora de billetes automática", valor_usd: 200, valor_pesos: 0, contacto_proveedor: "Distribuidor", categoria: "Herramientas" },
    { id: 3, item: "Juego de Escritorios y Sillas Oficina", valor_usd: 840, valor_pesos: 0, contacto_proveedor: "Muebles Paola", categoria: "Mobiliario" },
    { id: 4, item: "Herramientas de Taller y Unión Tools", valor_usd: 2060, valor_pesos: 0, contacto_proveedor: "Union Tools", categoria: "Taller" },
    { id: 5, item: "Cámaras de Seguridad HD", valor_usd: 400, valor_pesos: 0, contacto_proveedor: "Seguridad", categoria: "Seguridad" },
    { id: 6, item: "Desarrollo Web & Sistema NewPoint", valor_usd: 1750, valor_pesos: 0, contacto_proveedor: "Dev", categoria: "Software" }
  ]
};
